### ISSUE TITLE
Slow mobile experience for 1000+ sets to display

### ISSUE THREAD

**Issue by SeriousM** [jdknezek/mq-set-calc#1]
Hi, thanks for this wonderful tool!

I use it a lot on my mobile phone and sometimes I just want to find any combination containing a single skill eg. `DeathMarch`.
Since a lot of combinations allow `DeathMarch` with `Zomble` the result contains over 23k results.
Pressing "display xxx sets" results in a freeze of chrome for a few minutes because of the massive DOM manipulation.
- OPTION 1:
  We could add a pagination for every 200 elements on mobile devices?
- OPTION 2:
  We could try to fix the massive DOM manipulation by generating the table in memory and then just attach the table to the live DOM (so chrome has to deal only with a single dom operation).

What do you think about these two options?

I can help you if you like, you just need to point out the place where I can fix it.

**Comment by jdknezek** [comment]
I'm using React to handle DOM manipulation so I believe the operations are batched, but it is a gigantic reflow and definitetly slow on mobile. I added a dropdown for pagination every 100 items.
